# ZUGBRUECKE
# Calling routines in Windows DLLs from Python scripts running on unixlike systems
# https://github.com/pleiszenburg/zugbruecke
#
# 	.travis.yml: Configuration for Travis CI build test
#
# 	Required to run on platform / side: [UNIX]
#
# 	Copyright (C) 2017-2021 Sebastian M. Ernst <ernst@pleiszenburg.de>
#
# <LICENSE_BLOCK>
# The contents of this file are subject to the GNU Lesser General Public License
# Version 2.1 ("LGPL" or "License"). You may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
# https://github.com/pleiszenburg/zugbruecke/blob/master/LICENSE
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the
# specific language governing rights and limitations under the License.
# </LICENSE_BLOCK>


# Check this file at:
# http://lint.travis-ci.org/

# A virtual machine is required to run wine - is it?
sudo: enabled

# Repository language
language: python

# Python 3.4 is availabe for trusty and xenial, Python >= 3.5 xenial only
matrix:
    include:
        - dist: trusty
          python: "3.4"
          env:
              - ZUGBRUECKE__ISSUES_50_WORKAROUND=TRUE
              - ZUGBRUECKE_LOG_LEVEL=100
        - dist: xenial
          python: "3.5"
          env:
              - ZUGBRUECKE__ISSUES_50_WORKAROUND=FALSE
              - ZUGBRUECKE_LOG_LEVEL=100
        - dist: xenial
          python: "3.6"
          env:
              - ZUGBRUECKE__ISSUES_50_WORKAROUND=FALSE
              - ZUGBRUECKE_LOG_LEVEL=100
        - dist: xenial
          python: "3.7"
          env:
              - ZUGBRUECKE__ISSUES_50_WORKAROUND=FALSE
              - ZUGBRUECKE_LOG_LEVEL=100
        - dist: xenial
          python: "3.8"
          env:
              - ZUGBRUECKE__ISSUES_50_WORKAROUND=FALSE
              - ZUGBRUECKE_LOG_LEVEL=100

# Get wine and mingw cross compiler
# http://ubuntuhandbook.org/index.php/2017/01/install-wine-2-0-ubuntu-16-04-14-04-16-10/
# https://launchpad.net/~wine/+archive/ubuntu/wine-builds?field.series_filter=trusty
# https://dl.winehq.org/wine-builds/ubuntu/
before_install:
  - sudo dpkg --add-architecture i386
  - wget https://dl.winehq.org/wine-builds/Release.key
  - sudo apt-key add Release.key
  - wget https://dl.winehq.org/wine-builds/winehq.key
  - sudo apt-key add winehq.key
  - sudo apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu/'
  - sudo apt-get -qq update
  - sudo apt-get install -y wine-staging
  - export PATH=/opt/wine-staging/bin:$PATH
  - sudo apt-get install -y gcc-mingw-w64-i686
  - sudo apt-get install -y gcc-mingw-w64-x86-64
  - pip install -U pip
  - pip install -U setuptools
  - pip install -U pytest
  - wine --version
  - wine64 --version
  - i686-w64-mingw32-gcc --version
  - x86_64-w64-mingw32-gcc --version
  - python --version
  - pytest --version
  - uname -a
  - lsb_release -a

# command to install dependencies and module
install:
  # - make dll
  - make install

# command to run tests
script: make test

# Notify developers
notifications:
  email:
    recipients:
      - ernst@pleiszenburg.de
    on_success: always
    on_failure: always
